server:
  port: 8888
spring:
  application:
    name: autumn-config
  cloud:
    config:
      label: master
      server:
        git:
          search-paths: profile
          uri: https://github.com/qshui745/spring-cloud-config.git
          username: qshui745
          password: ewininfo123