server:
  port: 8888
spring:
  application:
    name: autumn-config
  cloud:
    config:
      label: master
      server:
        git:
          search-paths: profile
          uri: https://github.com/whli745/autumn.git
          username: whli745
          password: 5539044op
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/